"""
Copy the prompts for the `prompt output` files into the site's data.

The prompts are written and reviewed in one document,
`E:\\Profile Portfolio\\prompt-output-prompts.md`: one `## N. \\`file\\`` heading per
output, followed by a ```text block. This reads those blocks and writes them to
`src/data/output-prompts.ts`, keyed by output filename, so the site shows exactly
the text in the document and the two cannot drift apart.

    python scripts/sync-output-prompts.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOC = ROOT / "prompt-output-prompts.md"
OUT = ROOT / "portfolio" / "src" / "data" / "output-prompts.ts"
# The 15 files in `prompt output`, plus the two portfolio images written in the
# same document: the three-concept board, the GAMEVERSE portal and the two
# Abyssal Ventures submarine clips.
EXPECTED = 19

HEADING = re.compile(r"^## \d+\. `([^`]+)`", re.M)
BLOCK = re.compile(r"```text\n(.*?)\n```", re.S)


def main() -> None:
    text = DOC.read_text(encoding="utf-8")
    heads = list(HEADING.finditer(text))
    prompts: dict[str, str] = {}

    for i, head in enumerate(heads):
        # Only look inside this heading's own section, so a section that lost its
        # code block fails loudly instead of borrowing the next section's prompt.
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        block = BLOCK.search(text, head.end(), end)
        if not block:
            raise SystemExit(f"no ```text block under the heading for {head.group(1)}")
        prompts[head.group(1)] = block.group(1)

    if len(prompts) != EXPECTED:
        raise SystemExit(f"expected {EXPECTED} prompts, found {len(prompts)}: {sorted(prompts)}")

    lines = [
        "/**",
        " * Prompts for the files in `prompt output`, keyed by output filename.",
        " *",
        " * Generated by scripts/sync-output-prompts.py from prompt-output-prompts.md.",
        " * Edit the document and re-run the script; do not edit this file by hand.",
        " */",
        "export const outputPrompts = {",
    ]
    for name, prompt in prompts.items():
        # JSON string literals are valid JavaScript string literals.
        lines.append(f"  {json.dumps(name)}: {json.dumps(prompt, ensure_ascii=False)},")
    lines += ["} as const", "", "export type OutputFile = keyof typeof outputPrompts", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    for name, prompt in prompts.items():
        print(f"  {name:18s} {len(prompt):5d} chars")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
